version: "3.7"

services:
  example:
    container_name: angular-docker-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "4200:4200"
