version: "3.7"

services:
  example:
    container_name: angular-docker-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "80:80"
